INSERT INTO tb_category(name, created_At) VALUES ('Inteligência Artificial', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Internet das Coisas (IoT)', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Blockchain', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Realidade Virtual e Aumentada', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computação em Nuvem', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Impressão 3D', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Cibersegurança', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Big Data e Análise de Dados', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Robótica', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Tecnologia Vestível', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Assembly Language', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('C#', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('C++', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('COBOL', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Dart', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('F#', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Fortran', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Go', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Groovy', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Haskell', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Java', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('JavaScript', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Julia', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Kotlin', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Lisp', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Lua', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('MATLAB', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Objective-C', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Perl', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('PHP', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Python', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('R', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Ruby', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Rust', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Scala', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Shell Scripting', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('SQL', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Swift', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('TypeScript', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Realidade virtual e aumentada', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Inteligência artificial', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Drones', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Internet das Coisas (IoT)', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Big Data', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Impressão 3D', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Robótica', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Blockchain', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computação em nuvem', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Cibersegurança', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Realidade aumentada móvel (MAR)', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Realidade virtual móvel (MVR)', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Aprendizado de máquina (Machine Learning)', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Deep Learning', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Processamento de linguagem natural (NLP)', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computação quântica', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Edge Computing', NOW());