INSERT INTO tb_category(name, created_At) VALUES ('Inteligência Artificial', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Internet das Coisas (IoT)', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Blockchain', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Realidade Virtual e Aumentada', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computação em Nuvem', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Impressão 3D', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Cibersegurança', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Big Data e Análise de Dados', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Robótica', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Tecnologia Vestível', NOW());